name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  composer-phpcs-phpstan:
    uses: alleyinteractive/.github/.github/workflows/php-composer-command.yml@main
    with:
      php: 8.3
      command: |
        phpcs
        phpstan
